In [1]:
# Importing Library
import numpy as np

In [2]:
# Sigmoid Activation Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Forget Gate
def forget_gate(current_input_f, hidden_prev_f, bias_f, weight_f):
    # Concatenate the previous and current input
    concat = np.concatenate((current_input_f, hidden_prev_f), axis = 1)
    # Calculate the forget gate
    forget_gate = sigmoid(np.dot(concat, weight_f) + bias_f)
    return forget_gate

units = 4
features = 8
batch_size = 2

current_input_f = np.random.randn(batch_size, features)
hidden_prev_f = np.random.randn(batch_size, units)

bias_f = np.random.randn(1, units)
weight_f = np.random.randn(features + units, units)

f_t = forget_gate(current_input_f, hidden_prev_f, bias_f, weight_f)

print('Forget Gate Activation')
print('')
print(f_t)

Forget Gate Activation

[[0.09958527 0.98827425 0.07167689 0.1558788 ]
 [0.04493768 0.94296697 0.00372372 0.29403113]]


In [3]:
# Sigmoid Activation Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# TanH Activation Function
def tanh(x):
    return np.tanh(x)

# Input Gate
def input_gate(current_input_i, hidden_prev_i, bias_i, weight_i, weight_c, bias_c):
    # Concatenate the previous and current input
    concat = np.concatenate((current_input_i, hidden_prev_i), axis = 1)
    # Calculate the input gate
    input_gate = sigmoid(np.dot(concat, weight_i) + bias_i)
    # Calculate candidate cell
    candidate_cell = tanh(np.dot(concat, weight_c) + bias_c)
    
    return input_gate, candidate_cell

units = 4
features = 8
batch_size = 2

current_input_i = np.random.randn(batch_size, features)
hidden_prev_i = np.random.randn(batch_size, units)

bias_i = np.random.randn(1, units)
weight_i = np.random.randn(features + units, units)

bias_c = np.random.randn(1, units)
weight_c = np.random.randn(features + units, units)

i_t, c_t = input_gate(current_input_i, hidden_prev_i, bias_i, weight_i, weight_c, bias_c)

print('Input Gate Activation')
print('')
print(i_t)

print('')

print('Candidate State')
print('')
print(c_t)

Input Gate Activation

[[0.06491067 0.06447558 0.7342667  0.15732028]
 [0.11836995 0.05176911 0.97709341 0.99033942]]

Candidate State

[[ 0.99758758 -0.99957179 -0.99997947  0.99231992]
 [-0.99027171  0.90469623 -0.99544824  0.93204781]]


In [4]:
# Output Gate

def output_gate(current_input_o, hidden_prev_o, bias_o, weight_o, c_t):
    # Concatenate the previous and current input
    concat = np.concatenate((current_input_o, hidden_prev_o), axis = 1)
    # Calculate the output gate
    output_gate = sigmoid(np.dot(concat, weight_o) + bias_o)
    # Calculate the new hidden state
    h_t = output_gate * tanh(c_t)
    
    return h_t

c_t = np.random.randn(batch_size, units)

bias_o = np.random.randn(1, units)
weight_o = np.random.randn(features + units, units)

current_input_o = np.random.randn(batch_size, features)
hidden_prev_o = np.random.randn(batch_size, units)

h_t = output_gate(current_input_o, hidden_prev_o, bias_o, weight_o, c_t)

print('Output Gate Activation')
print('')
print(h_t)

Output Gate Activation

[[-0.01247277 -0.53977953  0.11343499 -0.33791311]
 [ 0.22399378 -0.0464726  -0.13359358  0.74558447]]
